myownproject/myownproject/urls.py
from django.conf.urls import patterns, include, url
from accounts.views import logout
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'myownproject.views.home', name='home'),
    # url(r'^myownproject/', include('myownproject.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^news/', include('news.urls', namespace='news')),
)

myownproject/news/urls.py
from django.conf.urls import patterns, url
from news import views
#from comments.views import add_comment


urlpatterns = patterns('',
	url(r'^(?P<news_id>\d+)/$', views.news_page, name='newspage'),
	url(r'^add_news/$', views.add_news, name='addnews'),
	url(r'^edit_news/(?P<news_id>\d+)/$', views.edit_news, name='editnews'),
	url(r'^tag/(?P<tag_id>\d+)/$', views.news_by_tag, name='tag'),
	url(r'^category/(?P<category_id>\d+)/$', views.news_by_cat, name='category'),
	#url(r'^(?P<news_id>\d+)/comment/$' , add_comment, name='addcomment')
	)

myownproject/news/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

class Category(models.Model):
	category = models.CharField(max_length=20)

	def __unicode__(self):
		return self.category

class Tag(models.Model):
	tag = models.CharField(max_length=30, blank=True)
	

	def __unicode__(self):
		return self.tag

class News(models.Model):
	title = models.CharField(max_length=80)
	category = models.ForeignKey(Category)
	author = models.ForeignKey(User)
	news_body = models.CharField(max_length=5000)
	pub_date = models.DateField('publication date',default = datetime.datetime.now())
	tags = models.ManyToManyField(Tag, blank=True)

	def __unicode__(self):
		return self.title

		

myownproject/news/forms.py
from django import forms
from django.forms import ModelForm
import datetime


from models import *


class AddNewsForm(ModelForm):
	class Meta():
		model = News
		exclude = ('author','tags')

class EditNewsForm(ModelForm):
	class Meta():
		model = News
		exclude = ('author', 'pub_date', 'tags')

		
class AddTagsForm(forms.Form):
	tags = forms.CharField(max_length=100)

myownproject/news/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from models import News, Category, Tag
from forms import AddNewsForm, AddTagsForm, EditNewsForm
from comments.models import Comment
from comments.forms import AddCommentForm
#from comments.views import add_comment


def news_page(request, news_id):
	news = News.objects.get(pk=news_id)
	tags = news.tags.all()
	category = news.category
	comments = news.comment_set.all()
	if request.method == 'POST':
		form = AddCommentForm(request.POST)
		if form.is_valid:
			comment = form.save(commit=False)
			comment.author = request.user
			comment.news = news
			comment.save()
	form = AddCommentForm()
	#form = add_comment(request, news.id)
	return render(request, 'news/news_page.html', {'form': form, 'news': news, 'tags': tags, 'category': category, 'user': request.user, 'comments': comments})
	

@login_required
def add_news(request):
	if request.method == "POST":
		form = AddNewsForm(request.POST)
		tform = AddTagsForm(request.POST or None)
		if form.is_valid():
			news = form.save(commit=False)
			tags = request.POST['tags'].split()
			news.author = request.user
			news.save()
			for tag in tags:
				new_tag = Tag(tag=tag)
				if Tag.objects.filter(tag=new_tag).exists():
					new_tag= Tag.objects.get(tag=tag)
				else:
					new_tag.save()
				news.tags.add(new_tag)
			messages.info(request, "You've successfully added news")
			return HttpResponseRedirect('/')
		else:
			messages.info(request, "Fill all fields")
	else:
		form = AddNewsForm()
	return render(request, 'news/add_news.html', {'form': form})

def edit_news(request, news_id):
	news = News.objects.get(pk=news_id)
	if request.method == "POST":
		form = EditNewsForm(request.POST, instance = news)
		if form.is_valid():
			news = form.save()
			messages.info(request, 'Your changes successfully saved')
			return HttpResponseRedirect('/news/%s/' %news.id)
		else:
			messages.info(request, "Fill all fields")
	else:
		form = EditNewsForm(instance = news)
	return render(request, 'news/edit_news.html', {'form': form})

def news_by_tag(request, tag_id):
	tag = Tag.objects.get(pk=tag_id)
	news = tag.news_set.all()
	return render(request, 'news/news_by_tag.html', {'tag': tag, 'news': news})

def news_by_cat(request, category_id):
	category = Category.objects.get(pk=category_id)
	news = category.news_set.all()
	return render(request, 'news/news_by_cat.html', {'category': category, 'news': news})
'''
def add_comment(request, news_id):
	news = News.objects.get(pk=news_id)
	if requesr.method == 'POST':
		form = AddCommentForm(request.POST)
		if form.is_valid:
			comment = form.save()
			comment.author = request.User
			comment.news = news
			comment.save()
			return HttpResponseRedirect(request, '/news/%s/' %news.id)
		else:
			message.info(request, 'Fill form correct')
	else:
		form = AddCommentForm()
	return HttpResponseRedirect(request, '/news/%s/' %news.id)
'''

myownproject/news/templates/news/add_news.html
{% extends 'base.html' %}

{% block title %}Add news{% endblock %}

{% block content %}
<form action='' method='post'>
	{% csrf_token %}
	{{ form.as_p }}
	<tform action='' method='post'>
		{% csrf_token %}
		<label for="id_tags">Tags</label>
		<input type=text name=tags>
	</tform>
<input type='submit' value='Save'>
</form>


{% endblock %}

myownproject/news/templates/news/edit_news.html
{% extends 'base.html' %}

{% block title %}Edit news{% endblock %}

{% block content %}
<form action='' method='post'>
	{% csrf_token %}
	{{ form.as_p }}
	<input type=submit vallue='Save'>
	
</form>


{% endblock %}

myownproject/news/templates/news/news_by_cat.html
{% extends 'base.html' %}
{% block title %}News by category{% endblock%}
{% block content %}
{% for n in news %}
	<p><a href="{% url 'news:newspage' n.id %}"> {{n.title}} </a></p>
{% endfor %}
{% endblock %}

myownproject/news/templates/news/news_by_tag.html
{% extends 'base.html' %}
{% block title %}News by tag{% endblock%}
{% block content %}
{% for n in news %}
	<p><a href="{% url 'news:newspage' n.id %}"> {{n.title}} </a></p>
{% endfor %}
{% endblock %}

myownproject/news/templates/news/news_page.html
{% extends 'base.html' %}

{% block title %} {{ news.title }}{% endblock %}

{% block content %}

<h1>{{ news.title }}</h1>
<a href="{% url 'news:category' category.id %}"><p>{{ news.category }}</p></a>
<p>{{ news.author }}</p>
<p>{{ news.news_body}}</p>
<p>{{ news.pub_date }}</p>

{% if tags %}
	Tags:
	{% for tag in tags %}
		<a href="{% url 'news:tag' tag.id %}">{{ tag }}</a>
	{% endfor %}
{% endif %}

{% if news.author == user %}
	<p><a href="{% url 'news:editnews' news.id %}">Edit news</a></p>
{% endif %}

{% if comments.exists %}
	{% for comment in comments %}
		<p> {{ comment.author }}</p>
		<p> {{ comment.comment_body }}</p>
		<p> {{ comment.pub_date }}</p>
	</br>
	{% endfor %}
{% endif %}
{% if user.is_authenticated %}
	<p>Add your comment:</p>
	<form action="{% url 'news:newspage' news.id %}" method='post'>
		{% csrf_token %}
		{{ form.comment_body }} <br/>
		<input type='submit' value='Comment' />
	</form>
{% endif %}
{% endblock %}

myownproject/news/templates/news/newspage.html
{% extends 'base.html' %}

{% block title %} {{ news.title }}{% endblock %}

{% block content %}

<h1>{{ news.title }}</h1>
<p>{{ news.category }}</p>
<p>{{ news.author }}</p>
<p>{{ news.news_body}}</p>
<p>{{ news.pub_date }}</p>

{% if tags %}
	{% for tag in tags %}
		{{ tag }}
	{% endfor %}
{% endif %}

{% if news.author == user %}
	<a href="{% url 'news:editnews' news.id %}">Edit news</a>
{% endif %}
	
{% endblock %}