myownproject/accounts/urls.py
from django.conf.urls import patterns, url
from accounts import views
from accounts.forms import LoginForm

urlpatterns = patterns('',
	url(r'^registration$', views.registration, name='registration'),
	url(r'^login$', views.login , name='login'),
	url(r'^logout$', views.logout, name='logout')
)

myownproject/myownproject/urls.py
from django.conf.urls import patterns, include, url
from accounts.views import logout
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'myownproject.views.home', name='home'),
    # url(r'^myownproject/', include('myownproject.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^news/', include('news.urls', namespace='news')),
)

myownproject/news/urls.py
from django.conf.urls import patterns, url
from news import views
#from comments.views import add_comment


urlpatterns = patterns('',
	url(r'^(?P<news_id>\d+)/$', views.news_page, name='newspage'),
	url(r'^add_news/$', views.add_news, name='addnews'),
	url(r'^edit_news/(?P<news_id>\d+)/$', views.edit_news, name='editnews'),
	url(r'^tag/(?P<tag_id>\d+)/$', views.news_by_tag, name='tag'),
	url(r'^category/(?P<category_id>\d+)/$', views.news_by_cat, name='category'),
	#url(r'^(?P<news_id>\d+)/comment/$' , add_comment, name='addcomment')
	)

myownproject/templates/base.html
<HTML>
<HEAD>
	<title>{% block title %} {% endblock %}</title>
</HEAD>
<BODY>
	<a href={% url 'home' %}>Home page</a>
	{% if not user.is_authenticated %}
	<a href="{% url 'accounts:registration' %}">Registration</a>
	<a href="{% url 'accounts:login' %}">Login</a>
	{% endif %}
	{% if user.is_authenticated %}
	<a href="{% url 'news:addnews' %}">Add news</a> 
	<a href="{% url 'accounts:logout' %}">Logout</a> {{ user.username }}
	{% endif %}
	{% if messages %}
	<ul>
		{% for message in messages %}
		<li>{{ message }}</li>
		{% endfor %}
	</ul>
	{% endif %}
	
	{% block content %}
	{% endblock %}
</BODY>

myownproject/templates/home.html
{% extends "base.html" %}

{% block title %}Home page{% endblock %}

{% block content %}
<h1>Our main page</h1>
	
	{% if news %}
		{% for one in news %}
			<p><a href="{% url 'news:newspage' one.id %}">{{ one.title }}</p>
		{% endfor %}
	{% endif %}
{% endblock %}